'use strict'
const express = require('express')
const rateLimit = require('express-rate-limit')
const fs = require('fs')
const path = require('path')
const os = require('os')
const { execFile } = require('child_process')

// Shared library helpers live with the create-custom-skills skill in
// ~/.agents/skills/. Fall back to the older ~/.duet/skills locations if absent.
function resolveScannerDir() {
  const candidates = [
    path.join(os.homedir(), '.agents', 'skills', 'create-custom-skills'),
    path.join(os.homedir(), '.duet', 'skills', 'create-custom-skills'),
    path.join(os.homedir(), '.duet', 'skills', 'library-scanner'),
  ]
  return candidates.find((d) => fs.existsSync(path.join(d, 'lib.js'))) || candidates[0]
}
const SCANNER_DIR = resolveScannerDir()
const lib = require(path.join(SCANNER_DIR, 'lib.js'))

const PORT = process.env.PORT || 4950
const app = express()
app.use(express.json())
app.use(express.static(path.join(__dirname, 'public')))

// --- Security: safe path resolution -----------------------------------------
// A user-supplied id (req.params.id) must never escape its intended base dir.
// Reject anything with path separators / traversal segments / nul bytes, then
// resolve and assert the final path stays strictly inside baseDir. Returns the
// absolute child dir on success, or null if the id is unsafe / out of bounds.
function safeChildDir(baseDir, id) {
  const raw = String(id == null ? '' : id)
  // Whitelist: ids are slugs (see slugify). Anything with separators, traversal
  // dots, leading dots, nul bytes, or non-slug chars is rejected outright.
  if (!raw || raw.length > 200) return null
  if (raw.includes('/') || raw.includes('\\') || raw.includes('\0')) return null
  if (raw === '.' || raw === '..' || raw.includes('..')) return null
  if (!/^[a-zA-Z0-9._-]+$/.test(raw)) return null
  const base = path.resolve(baseDir)
  const full = path.resolve(base, raw)
  // Must be a direct child strictly inside base (path.sep guards prefix matches).
  if (full !== path.join(base, raw)) return null
  if (!full.startsWith(base + path.sep)) return null
  return full
}

// --- Security: rate limiting via express-rate-limit --------------------------
// express-rate-limit is the standard, well-modeled limiter (CodeQL recognizes
// it). In-memory store is fine for this single-process local app. General
// read/write API limit, plus a stricter limit for the expensive /api/scan
// handler (shells out to scanner + enrichment). /healthz is never rate limited
// so it stays a fast, unlimited liveness probe.
const apiLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 120,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'rate limit exceeded, try again later' },
})
const scanLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 6,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'rate limit exceeded, try again later' },
})

const AGENTS_SKILLS_DIR = path.join(os.homedir(), '.agents', 'skills')

// Directories that may hold an installed skill's SKILL.md, checked in order.
const SKILL_SOURCE_DIRS = [
  path.join(os.homedir(), '.agents', 'skills'),
  path.join(os.homedir(), '.claude', 'skills'),
  path.join(os.homedir(), '.duet', 'skills'),
]

// Composio provider -> the connected app it exposes (TYPE=Integration tools).
const COMPOSIO_TOOL_NAMES = {
  gmail: 'Gmail',
  slack: 'Slack',
  stripe: 'Stripe',
  google_search_console: 'Google Search Console',
}

// --- Enrichment: TYPE (deterministic) + TOOLS (inferred) ---------------------

// Field 1 — TYPE from `source`, no inference.
function computeType(source) {
  const s = String(source || '')
  if (s.startsWith('composio:')) return 'Integration'
  if (s.startsWith('installed:')) return 'Duet skill'
  return 'Custom'
}

// Resolve the on-disk SKILL.md for an installed skill. `installed:<name>` maps
// to <dir>/<name>/SKILL.md across the agents/claude/duet skill dirs.
function resolveSkillMdPath(source, fallbackName) {
  const src = String(source || '')
  const name = src.startsWith('installed:') ? src.slice('installed:'.length) : fallbackName
  if (!name) return null
  for (const base of SKILL_SOURCE_DIRS) {
    const p = path.join(base, name, 'SKILL.md')
    if (fs.existsSync(p)) return p
  }
  return null
}

// Cache parsed SKILL.md text by path+mtime so we don't re-read ~85 files/request.
const mdCache = new Map()
function readSkillMd(p) {
  try {
    const mtime = fs.statSync(p).mtimeMs
    const hit = mdCache.get(p)
    if (hit && hit.mtime === mtime) return hit.text
    const text = fs.readFileSync(p, 'utf8')
    mdCache.set(p, { mtime, text })
    return text
  } catch {
    return ''
  }
}

// --- AI tools cache (generated by enrich-tools.js, never per-request) ---------
// tools-cache.json maps `source` -> { tools, hash, generatedAt }. Loaded once
// into memory (refreshed on mtime change) and merged onto each skill by source.
// NO AI is called inline during a request.
const TOOLS_CACHE_FILE = path.join(__dirname, 'tools-cache.json')
let toolsCache = { data: {}, mtime: 0 }
function getToolsCache() {
  try {
    const mtime = fs.statSync(TOOLS_CACHE_FILE).mtimeMs
    if (mtime !== toolsCache.mtime) {
      toolsCache = { data: JSON.parse(fs.readFileSync(TOOLS_CACHE_FILE, 'utf8')) || {}, mtime }
    }
  } catch {
    toolsCache = { data: {}, mtime: 0 }
  }
  return toolsCache.data
}

// Soft fallback ONLY for cache misses — keyword inference of external
// dependencies from SKILL.md text. Collect ALL matching external categories;
// 'Code' is a fallback only when none of them do.
function inferToolsFromText(text) {
  const t = String(text || '')
  const tools = []
  // GitHub: require github.com or a real `gh <subcommand>` (bare "gh "/"github"
  // over-match "high"/"through" and Firecrawl's `github` search category).
  if (/github\.com|\bgh\s+(api|pr|run|view|repo|issue|auth|clone|cli|checkout|push|pull|merge|status|browse|label|workflow|release|gist|search)\b/i.test(t)) tools.push('GitHub')
  // Web: scraping / search / SEO data.
  const isWebScrape = /firecrawl|scrape|crawl|web search|dataforseo|builtwith/i.test(t)
  if (isWebScrape) tools.push('Web')
  // Composio (the meta integration layer, distinct from a composio: source).
  if (/\bcomposio\b/i.test(t)) tools.push('Composio')
  // Media / AI generation.
  if (/ai gateway|gpt image|elevenlabs|text-to-speech|seedance|fal\.ai|nano banana/i.test(t)) tools.push('Media/AI')
  // Email delivery.
  if (/\bresend\b|newsletter|broadcast/i.test(t)) tools.push('Email')
  // Browser automation. gstack/browse-daemon are strong signals; a lone
  // "playwright" mention inside a web-scraping skill (Firecrawl) is incidental,
  // so only count playwright when the skill isn't primarily web scraping.
  if (/gstack|browse daemon|headless browser/i.test(t) || (/\bplaywright\b/i.test(t) && !isWebScrape)) tools.push('Browser')
  // Code: only when no external service matched but it clearly builds/edits code.
  if (tools.length === 0 && /worktree|bun run|bun format|npm run|pnpm |check-types|eslint|prettier|pytest|\btsc\b|lint-staged|```bash|```python|```typescript|```sh\b/i.test(t)) tools.push('Code')
  return tools
}

// Compute TOOLS for one skill meta. Primary source is the AI-generated cache
// (tools-cache.json, keyed by source). Composio stays deterministic from source.
// On a cache miss we fall back to keyword inference (never inline AI), and only
// for installed skills with a resolvable SKILL.md.
function computeTools(meta) {
  const src = String(meta.source || '')
  const cached = getToolsCache()[src]
  if (cached && Array.isArray(cached.tools)) return cached.tools
  // Cache miss — keep the app deterministic and degrade gracefully otherwise.
  if (src.startsWith('composio:')) {
    const app = src.slice('composio:'.length)
    return [COMPOSIO_TOOL_NAMES[app] || titleCaseApp(app)]
  }
  const p = resolveSkillMdPath(src, meta.name)
  if (!p) return []
  return inferToolsFromText(readSkillMd(p))
}

function titleCaseApp(s) {
  return String(s || '').split(/[_\s-]+/).filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
}

// Return a shallow copy of a skill meta with `type` and `tools` added.
function enrichSkill(meta) {
  try {
    return { ...meta, type: computeType(meta.source), tools: computeTools(meta) }
  } catch {
    return { ...meta, type: computeType(meta.source), tools: [] }
  }
}

function slugify(name) {
  return String(name || 'skill')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'skill'
}

// --- API: full library index -------------------------------------------------
app.get('/api/library', apiLimiter, (req, res) => {
  try {
    // Always read fresh from disk so manual scans/seeds are reflected.
    const index = fs.existsSync(lib.INDEX_FILE)
      ? lib.readJSON(lib.INDEX_FILE)
      : lib.regenerateIndex()
    // Enrich every skill with TYPE (from source) + TOOLS (inferred) so the
    // collapsed cards render without lazy-fetching. Index format on disk is
    // untouched; enrichment lives only in the response layer.
    const enriched = { ...index, skills: (index.skills || []).map(enrichSkill) }
    res.json(enriched)
  } catch (e) {
    res.status(500).json({ error: e.message })
  }
})

// --- API: single skill (meta + SKILL.md) -------------------------------------
app.get('/api/skills/:id', apiLimiter, (req, res) => {
  const dir = safeChildDir(lib.SKILLS_DIR, req.params.id)
  if (!dir) return res.status(404).json({ error: 'skill not found' })
  const meta = lib.readJSON(path.join(dir, 'meta.json'))
  if (!meta) return res.status(404).json({ error: 'skill not found' })
  let skillMd = ''
  try { skillMd = fs.readFileSync(path.join(dir, 'SKILL.md'), 'utf8') } catch {}
  res.json({ meta: enrichSkill(meta), skillMd })
})

// --- API: single board (meta + definition.json) ------------------------------
app.get('/api/boards/:id', apiLimiter, (req, res) => {
  const dir = safeChildDir(lib.BOARDS_DIR, req.params.id)
  if (!dir) return res.status(404).json({ error: 'board not found' })
  const meta = lib.readJSON(path.join(dir, 'meta.json'))
  if (!meta) return res.status(404).json({ error: 'board not found' })
  const definition = lib.readJSON(path.join(dir, 'definition.json'), {})
  res.json({ meta, definition })
})

// --- API: publish a draft skill into ~/.agents/skills/ -----------------------
app.post('/api/skills/:id/publish', apiLimiter, (req, res) => {
  try {
    const dir = safeChildDir(lib.SKILLS_DIR, req.params.id)
    if (!dir) return res.status(404).json({ error: 'skill not found' })
    const meta = lib.readJSON(path.join(dir, 'meta.json'))
    if (!meta) return res.status(404).json({ error: 'skill not found' })
    const skillMdPath = path.join(dir, 'SKILL.md')
    if (!fs.existsSync(skillMdPath)) return res.status(400).json({ error: 'no SKILL.md to publish' })
    const skillMd = fs.readFileSync(skillMdPath, 'utf8')

    // Install via direct copy into ~/.agents/skills/<slug>/SKILL.md
    const slug = slugify(meta.name)
    const destDir = path.join(AGENTS_SKILLS_DIR, slug)
    fs.mkdirSync(destDir, { recursive: true })
    fs.writeFileSync(path.join(destDir, 'SKILL.md'), skillMd)

    // Update meta -> published, regen index
    meta.status = 'published'
    meta.publishedAt = new Date().toISOString()
    meta.installedPath = path.join(destDir, 'SKILL.md')
    lib.writeJSON(path.join(dir, 'meta.json'), meta)
    const index = lib.regenerateIndex()
    res.json({ ok: true, meta, installedPath: meta.installedPath, counts: index.counts })
  } catch (e) {
    res.status(500).json({ error: e.message })
  }
})

// --- API: trigger a scan ------------------------------------------------------
app.post('/api/scan', scanLimiter, (req, res) => {
  const args = req.body && req.body.noAi ? ['scan.js', '--no-ai'] : ['scan.js']
  execFile('node', args, { cwd: SCANNER_DIR, timeout: 150000, maxBuffer: 4 * 1024 * 1024 }, (err, stdout, stderr) => {
    const index = lib.regenerateIndex()
    // Refresh AI tool classifications for any new/changed skills (fire-and-forget;
    // idempotent + content-hashed, so this only (re)classifies what changed).
    execFile('node', ['enrich-tools.js'], { cwd: __dirname, timeout: 150000, maxBuffer: 4 * 1024 * 1024 }, (e2) => {
      if (e2) console.error('enrich-tools after scan failed:', e2.message)
    })
    // Also mine conversations + tools and synthesize composite skill proposals
    // (fire-and-forget; idempotent by source). Re-enrich afterward so the new
    // drafts pick up tool pills. Never blocks the scan response or /healthz.
    const proposeArgs = req.body && req.body.noAi ? ['propose-skills.js', '--no-ai'] : ['propose-skills.js']
    execFile('node', proposeArgs, { cwd: SCANNER_DIR, timeout: 150000, maxBuffer: 4 * 1024 * 1024 }, (e3) => {
      if (e3) return console.error('propose-skills after scan failed:', e3.message)
      execFile('node', ['enrich-tools.js'], { cwd: __dirname, timeout: 150000, maxBuffer: 4 * 1024 * 1024 }, (e4) => {
        if (e4) console.error('enrich-tools after proposals failed:', e4.message)
      })
    })
    if (err) {
      return res.status(500).json({ error: err.message, stdout, stderr, counts: index.counts })
    }
    res.json({ ok: true, output: stdout, counts: index.counts })
  })
})

app.get('/healthz', (req, res) => res.json({ ok: true }))

app.listen(PORT, () => console.log(`Skills & Boards Library on :${PORT}`))
