/**
 * Walk skills/ and emit src/generated.ts — a typed registry of every Skill.
 *
 * Run via `bun run build:registry`.
 *
 * Validations:
 *  - SKILL.md frontmatter must have id, name, description (strings).
 *  - Folder name must equal frontmatter id (folder == id by convention).
 *  - id must be unique across the registry.
 *  - Optional model is a string; optional tools is a string[].
 *  - Body must not be empty.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'
import matter from 'gray-matter'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const SKILLS_DIR = join(ROOT, 'skills')
const OUT = join(ROOT, 'src', 'generated.ts')
const USE_CASES_FILE = join(ROOT, 'src', 'use-cases.ts')

interface ParsedSkill {
  id: string
  name: string
  description: string
  model?: string
  tools?: string[]
  body: string
}

function parseSkillDir(dir: string): ParsedSkill {
  const folder = basename(dir)
  const skillPath = join(dir, 'SKILL.md')
  const raw = readFileSync(skillPath, 'utf8')
  const { data, content } = matter(raw)

  const requireString = (k: string): string => {
    const v = data[k]
    if (typeof v !== 'string' || !v.trim()) {
      throw new Error(`${skillPath}: frontmatter '${k}' must be a non-empty string`)
    }
    return v
  }

  const id = requireString('id')
  const name = requireString('name')
  const description = requireString('description')

  if (id !== folder) {
    throw new Error(
      `${skillPath}: frontmatter id '${id}' does not match folder name '${folder}'. ` +
        `Folder == id by convention.`,
    )
  }

  const body = content.trim()
  if (!body) throw new Error(`${skillPath}: body is empty`)

  const model = data.model
  if (model !== undefined && typeof model !== 'string') {
    throw new Error(`${skillPath}: 'model' must be a string if present`)
  }

  const tools = data.tools
  if (tools !== undefined) {
    if (!Array.isArray(tools) || tools.some((t) => typeof t !== 'string')) {
      throw new Error(`${skillPath}: 'tools' must be a string[] if present`)
    }
  }

  return {
    id,
    name,
    description,
    ...(typeof model === 'string' ? { model } : {}),
    ...(Array.isArray(tools) ? { tools: tools as string[] } : {}),
    body,
  }
}

function discoverSkills(): ParsedSkill[] {
  const entries = readdirSync(SKILLS_DIR)
  const skills: ParsedSkill[] = []
  for (const entry of entries) {
    const full = join(SKILLS_DIR, entry)
    if (!statSync(full).isDirectory()) continue
    skills.push(parseSkillDir(full))
  }
  return skills.sort((a, b) => a.id.localeCompare(b.id))
}

function loadKnownExternalIds(): Set<string> {
  // Read external-skills.ts and pull the literal id list out. We don't
  // import it because this is a build script and the source may not be
  // built yet.
  const file = join(ROOT, 'src', 'external-skills.ts')
  const raw = readFileSync(file, 'utf8')
  const re = /'([a-z0-9-]+)'/g
  const ids = new Set<string>()
  // Anchor parsing to the KNOWN_DEFAULT_SKILL_IDS array.
  const block = raw.match(/KNOWN_DEFAULT_SKILL_IDS\s*=\s*\[([^\]]*)\]/s)?.[1] ?? ''
  let m: RegExpExecArray | null
  while ((m = re.exec(block))) ids.add(m[1]!)
  return ids
}

function assertUseCaseSkillIdsResolve(skills: ParsedSkill[]): void {
  // Best-effort static check: scan use-cases.ts for primarySkillId / supporting
  // skill id literals and confirm each is either a local skill or a known
  // external (default) skill id. Misses dynamic refs; defense-in-depth only.
  let raw: string
  try {
    raw = readFileSync(USE_CASES_FILE, 'utf8')
  } catch {
    return
  }
  const local = new Set(skills.map((s) => s.id))
  const external = loadKnownExternalIds()
  const referenced = new Set<string>()

  // primarySkillId: 'X'
  const primaryRe = /primarySkillId:\s*['"]([^'"]+)['"]/g
  let m: RegExpExecArray | null
  while ((m = primaryRe.exec(raw))) referenced.add(m[1]!)

  // supportingSkillIds: ['X', 'Y'] — extract everything inside the brackets
  const supportingRe = /supportingSkillIds:\s*\[([^\]]*)\]/g
  while ((m = supportingRe.exec(raw))) {
    const block = m[1]!
    const idRe = /'([^']+)'|"([^"]+)"/g
    let idMatch: RegExpExecArray | null
    while ((idMatch = idRe.exec(block))) referenced.add((idMatch[1] ?? idMatch[2])!)
  }

  const unknown = [...referenced].filter((r) => !local.has(r) && !external.has(r))
  if (unknown.length > 0) {
    throw new Error(
      `use-cases.ts references unknown skill id(s): ${unknown.join(', ')}. ` +
        `Known local ids: ${[...local].join(', ')}. ` +
        `Known external (default) ids: ${[...external].join(', ')}. ` +
        `If this is a new chat-app default skill, add it to src/external-skills.ts.`,
    )
  }
}

function emit(skills: ParsedSkill[]): string {
  const header = `// Generated by scripts/build-registry.ts — do not edit manually.\n// Run 'bun run build:registry' to regenerate.\n\nimport type { Skill } from './types.js'\n\nexport const SKILLS: readonly Skill[] = ${JSON.stringify(skills, null, 2)} as const\n`
  return header
}

function main(): void {
  const skills = discoverSkills()

  const seen = new Set<string>()
  for (const s of skills) {
    if (seen.has(s.id)) throw new Error(`duplicate skill id: ${s.id}`)
    seen.add(s.id)
  }

  assertUseCaseSkillIdsResolve(skills)

  writeFileSync(OUT, emit(skills))
  console.log(`generated ${skills.length} skill(s) → src/generated.ts`)
}

main()
